version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i yarn@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build:$ENVIRONMENT
  post_build:
    commands:
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared.
      - aws s3 cp build s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
