version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i yarn@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build:$ENVIRONMENT
