version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i yarn@latest -g
      - yarn add gatsby
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo Accessing bucket ${S3_BUCKET}
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo S3 bucket is cleared.
      - aws s3 sync ./public s3://${S3_BUCKET} --delete
      - echo Build completed on `date`
